name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: federated-ontologies
      uses: TheDoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'ontologies.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: actions/upload-artifact@v2
      with:
        name: federated-ontologies
        path: ./ontologies.zip
